### ISSUE TITLE
ModuleNotFoundError: No module named 'nonebot.adapters.cqhttp.event'

### ISSUE THREAD

**Issue by Ikaros-521** [Lancercmd/nonebot_plugin_translator#20]
```python3
08-10 16:12:02 [ERROR] nonebot | Failed to import "nonebot_plugin_translator"
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\py38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\py38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Anaconda3\envs\py38\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\Anaconda3\envs\py38\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Anaconda3\envs\py38\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Anaconda3\envs\py38\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Anaconda3\envs\py38\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "D:\Anaconda3\envs\py38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\python-pro\NoneBot2\test1\.\bot.py", line 24, in <module>
    nonebot.load_plugin("nonebot_plugin_translator")
  File "D:\Anaconda3\envs\py38\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "D:\Anaconda3\envs\py38\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "D:\Anaconda3\envs\py38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\Anaconda3\envs\py38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Anaconda3\envs\py38\lib\site-packages\nonebot_plugin_translator\__init__.py", line 21, in <module>
    from nonebot.adapters.cqhttp.event import (GroupMessageEvent, MessageEvent,
ModuleNotFoundError: No module named 'nonebot.adapters.cqhttp.event'
```

**Comment by Lancercmd** [comment]
非最新版本，从插件的 [2.0.0b1.post1](https://pypi.org/project/nonebot-plugin-translator/2.0.0b1.post1/) 版本开始，要求 Python 版本 >= 3.9 才可被查询到或安装/更新。
> 若执意使用旧版本插件，应自行安装对应的依赖或将依赖降级至对应版本。

**Comment by Ikaros-521** [comment]
> 非最新版本，从插件的 [2.0.0b1.post1](https://pypi.org/project/nonebot-plugin-translator/2.0.0b1.post1/) 版本开始，要求 Python 版本 >= 3.9 才可被查询到或安装/更新。
> 
> > 若执意使用旧版本插件，应自行安装对应的依赖或将依赖降级至对应版本。

好的，谢谢
